//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginProvider.Commands
{
    public interface IFuncCommand<out TResult>
    {
    	TResult Execute();
    }
    public interface IFuncCommand<in T, out TResult>
    {
    	TResult Execute(T arg);
    }
    public interface IFuncCommand<in T1, in T2, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2);
    }
    public interface IFuncCommand<in T1, in T2, in T3, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, in T12, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, in T12, in T13, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, in T12, in T13, in T14, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, in T12, in T13, in T14, in T15, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15);
    }
    public interface IFuncCommand<in T1, in T2, in T3, in T4, in T5, in T6, in T7, in T8, in T9, in T10, in T11, in T12, in T13, in T14, in T15, in T16, out TResult>
    {
    	TResult Execute(T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9, T10 arg10, T11 arg11, T12 arg12, T13 arg13, T14 arg14, T15 arg15, T16 arg16);
    }
}
